package pe.edu.unsch.entities;
// Generated 17-jul-2019 1:08:02 by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Brand generated by hbm2java
 */
@Entity
@Table(name = "brand", catalog = "divisimabd")
public class Brand implements java.io.Serializable {

	private int idbrand;
	private String name;

	public Brand() {
	}

	public Brand(int idbrand, String name) {
		this.idbrand = idbrand;
		this.name = name;
	}

	@Id

	@Column(name = "idbrand", unique = true, nullable = false)
	public int getIdbrand() {
		return this.idbrand;
	}

	public void setIdbrand(int idbrand) {
		this.idbrand = idbrand;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
