package pe.edu.unsch.entities;
// Generated 17-jul-2019 1:08:02 by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Colour generated by hbm2java
 */
@Entity
@Table(name = "colour", catalog = "divisimabd")
public class Colour implements java.io.Serializable {

	private int idcolour;
	private String name;

	public Colour() {
	}

	public Colour(int idcolour, String name) {
		this.idcolour = idcolour;
		this.name = name;
	}

	@Id

	@Column(name = "idcolour", unique = true, nullable = false)
	public int getIdcolour() {
		return this.idcolour;
	}

	public void setIdcolour(int idcolour) {
		this.idcolour = idcolour;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
