package pe.edu.unsch.entities;
// Generated 17-jul-2019 1:08:02 by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Partner generated by hbm2java
 */
@Entity
@Table(name = "partner", catalog = "divisimabd")
public class Partner implements java.io.Serializable {

	private int idpartner;
	private String name;

	public Partner() {
	}

	public Partner(int idpartner, String name) {
		this.idpartner = idpartner;
		this.name = name;
	}

	@Id

	@Column(name = "idpartner", unique = true, nullable = false)
	public int getIdpartner() {
		return this.idpartner;
	}

	public void setIdpartner(int idpartner) {
		this.idpartner = idpartner;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
