package pe.edu.unsch.entities;
// Generated 17-jul-2019 1:08:02 by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProductId generated by hbm2java
 */
@Embeddable
public class ProductId implements java.io.Serializable {

	private int idproduct;
	private String idcategory;
	private String idpartner;
	private String idbrand;
	private String idcolour;

	public ProductId() {
	}

	public ProductId(int idproduct, String idcategory, String idpartner, String idbrand, String idcolour) {
		this.idproduct = idproduct;
		this.idcategory = idcategory;
		this.idpartner = idpartner;
		this.idbrand = idbrand;
		this.idcolour = idcolour;
	}

	@Column(name = "idproduct", nullable = false)
	public int getIdproduct() {
		return this.idproduct;
	}

	public void setIdproduct(int idproduct) {
		this.idproduct = idproduct;
	}

	@Column(name = "idcategory", nullable = false, length = 45)
	public String getIdcategory() {
		return this.idcategory;
	}

	public void setIdcategory(String idcategory) {
		this.idcategory = idcategory;
	}

	@Column(name = "idpartner", nullable = false, length = 45)
	public String getIdpartner() {
		return this.idpartner;
	}

	public void setIdpartner(String idpartner) {
		this.idpartner = idpartner;
	}

	@Column(name = "idbrand", nullable = false, length = 45)
	public String getIdbrand() {
		return this.idbrand;
	}

	public void setIdbrand(String idbrand) {
		this.idbrand = idbrand;
	}

	@Column(name = "idcolour", nullable = false, length = 45)
	public String getIdcolour() {
		return this.idcolour;
	}

	public void setIdcolour(String idcolour) {
		this.idcolour = idcolour;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProductId))
			return false;
		ProductId castOther = (ProductId) other;

		return (this.getIdproduct() == castOther.getIdproduct())
				&& ((this.getIdcategory() == castOther.getIdcategory()) || (this.getIdcategory() != null
						&& castOther.getIdcategory() != null && this.getIdcategory().equals(castOther.getIdcategory())))
				&& ((this.getIdpartner() == castOther.getIdpartner()) || (this.getIdpartner() != null
						&& castOther.getIdpartner() != null && this.getIdpartner().equals(castOther.getIdpartner())))
				&& ((this.getIdbrand() == castOther.getIdbrand()) || (this.getIdbrand() != null
						&& castOther.getIdbrand() != null && this.getIdbrand().equals(castOther.getIdbrand())))
				&& ((this.getIdcolour() == castOther.getIdcolour()) || (this.getIdcolour() != null
						&& castOther.getIdcolour() != null && this.getIdcolour().equals(castOther.getIdcolour())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdproduct();
		result = 37 * result + (getIdcategory() == null ? 0 : this.getIdcategory().hashCode());
		result = 37 * result + (getIdpartner() == null ? 0 : this.getIdpartner().hashCode());
		result = 37 * result + (getIdbrand() == null ? 0 : this.getIdbrand().hashCode());
		result = 37 * result + (getIdcolour() == null ? 0 : this.getIdcolour().hashCode());
		return result;
	}

}
