package pe.edu.unsch.entities;
// Generated 17-jul-2019 1:08:02 by Hibernate Tools 5.1.7.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", catalog = "divisimabd")
public class Product implements java.io.Serializable {

	private ProductId id;
	private String name;
	private String price;
	private String quantity;
	private String description;
	private String urlimage;
	private String feature;

	public Product() {
	}

	public Product(ProductId id, String name, String price, String quantity, String description, String urlimage,
			String feature) {
		this.id = id;
		this.name = name;
		this.price = price;
		this.quantity = quantity;
		this.description = description;
		this.urlimage = urlimage;
		this.feature = feature;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idproduct", column = @Column(name = "idproduct", nullable = false)),
			@AttributeOverride(name = "idcategory", column = @Column(name = "idcategory", nullable = false, length = 45)),
			@AttributeOverride(name = "idpartner", column = @Column(name = "idpartner", nullable = false, length = 45)),
			@AttributeOverride(name = "idbrand", column = @Column(name = "idbrand", nullable = false, length = 45)),
			@AttributeOverride(name = "idcolour", column = @Column(name = "idcolour", nullable = false, length = 45)) })
	public ProductId getId() {
		return this.id;
	}

	public void setId(ProductId id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "price", nullable = false, length = 45)
	public String getPrice() {
		return this.price;
	}

	public void setPrice(String price) {
		this.price = price;
	}

	@Column(name = "quantity", nullable = false, length = 45)
	public String getQuantity() {
		return this.quantity;
	}

	public void setQuantity(String quantity) {
		this.quantity = quantity;
	}

	@Column(name = "description", nullable = false, length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "urlimage", nullable = false, length = 45)
	public String getUrlimage() {
		return this.urlimage;
	}

	public void setUrlimage(String urlimage) {
		this.urlimage = urlimage;
	}

	@Column(name = "feature", nullable = false, length = 45)
	public String getFeature() {
		return this.feature;
	}

	public void setFeature(String feature) {
		this.feature = feature;
	}

}
